export const characterData: {
  id: string;
  nametag: string;
  characterImg: string;
  facesImg: string;
  avatar: string;
  desc: string;
}[] = [
  {
    id: '1',
    nametag: 'RUDEUS GREYRAT',
    characterImg: '/images/characterDescription/rudeus/character.png',
    facesImg: '/images/characterDescription/rudeus/faces.png',
    avatar: '/images/character/rudeus.png',
    desc: 'His nickname is Rudy. He is the eldest son of the Greyrat family, a low-ranking noble family that governs the village of Buena, a small village in the Fitora domain of the Kingdom of Asura.\nIn his previous life, he was a 34-year-old unemployed virgin hermit who was kicked out of his home, but upon his reincarnation, he decided to live for real this time.\n On the surface, he acts serious, but on the inside he is a scruffy man as he is, and he is sometimes unable to hide his inner life.',
  },
  {
    id: '2',
    nametag: 'NO NAME',
    characterImg: '/images/characterDescription/noname/character.png',
    facesImg: '',
    avatar: '/images/character/noname.png',
    desc: 'He is a 34-year-old unemployed virgin recluse. He was kicked out of his house, and shortly afterwards he died in an accident while trying to save a high school student who was about to be hit by a truck, and was reincarnated as Rudeus Greyrat. Taking the opportunity of his reincarnation, he decides to live seriously this time.',
  },
  {
    id: '3',
    nametag: 'ROXY MIGURDIA',
    characterImg: '/images/characterDescription/roxy/character.png',
    facesImg: '/images/characterDescription/roxy/faces.png',
    avatar: '/images/character/roxy.png',
    desc: "She is a water king class magician of the 'Migurd' demon tribe. She is a long-lived Migurd and looks like a beautiful girl with jittery eyes and blue hair, but she is an adult. She was invited to the Greyrat family as Rudy's magic tutor and is Rudeus' mentor. Upon learning of the Fitoa teleportation incident, she joins former Paul associates Elinalise and Talhand in the search for Rudeus and his friends.",
  },
  {
    id: '4',
    nametag: 'SYLPHIETTE',
    characterImg: '/images/characterDescription/sylphy/character.png',
    facesImg: '/images/characterDescription/sylphy/faces.png',
    avatar: '/images/character/sylphy.png',
    desc: "The elf-eared childhood friend in the village of Buena. Her nickname is 'Sylphy'. When she was bullied, Rudy rescued her and became his first friend. She is interested in magic and learns it from Rudy.",
  },
  {
    id: '5',
    nametag: 'ERIS BOREAS GREYRAT',
    characterImg: '/images/characterDescription/eris/character.png',
    facesImg: '/images/characterDescription/eris/faces.png',
    avatar: '/images/character/eris.png',
    desc: "Daughter of the mayor of Roa, a large city in the territory of Fitoa. She is a beautiful red-haired girl with an unimaginably ferocious personality. She has a great talent with the sword, but she is not good at studying. She was studying under Rudeus, but was sent to the Demon's Continent with Rudeus after the transfer to Fitoa, where she and Ruijerd formed the adventurer party 'Dead End' and aim to return to the Kingdom of Asura.",
  },
  {
    id: '6',
    nametag: 'RUIJERD SUPERDIA',
    characterImg: '/images/characterDescription/ruijerd/character.png',
    facesImg: '/images/characterDescription/ruijerd/faces.png',
    avatar: '/images/character/ruijerd.png',
    desc: "He is a warrior of the Superd, a demon tribe known as the 'Dead End'.He has emerald green hair and a red jewel on his forehead. He is taciturn and stubborn. He helps Rudeus and Eris, who have been sent to the Demon Continent, and the three of them form the adventurer party 'Dead End', aiming to return them safely to the Kingdom of Asura.",
  },
  {
    id: '7',
    nametag: 'PAUL GREYRAT',
    characterImg: '/images/characterDescription/paul/character.png',
    facesImg: '/images/characterDescription/paul/faces.png',
    avatar: '/images/character/paul.png',
    desc: "Father of Rudeus. A knight stationed in the village of Buena, he is an excellent swordsman. On the other hand, he is sloppy with women and easily offended. He is a former member of the adventurer party 'Black Wolf Fang'. He is searching for his family, who went missing in the Fitoa territory transfer incident.",
  },
  {
    id: '8',
    nametag: 'ZENITH GREYRAT',
    characterImg: '/images/characterDescription/zenith/character.png',
    facesImg: '/images/characterDescription/zenith/faces.png',
    avatar: '/images/character/zenith.png',
    desc: "Mother of Rudeus. She specializes in healing magic. She is caring and cheerful, but also has a hysterical side. She is a former member of the adventurer party 'Black Wolf Fang'. She gave birth to a daughter, Norn. Her whereabouts are unknown after the Fitoa territory transfer incident.",
  },
  {
    id: '9',
    nametag: 'LILIA GREYRAT',
    characterImg: '/images/characterDescription/lilia/character.png',
    facesImg: '/images/characterDescription/lilia/faces.png',
    avatar: '/images/character/lilia.png',
    desc: "She is a maid in the Greyrat family and diligent in her work. She feels creeped out by Rudeus's childish behavior and keeps her distance from him, but she respects him after he helps her when she gets pregnant after having an affair with Paul. She gives birth to a daughter, Aisha. Moved to the Kingdom of Shirone with Aisha after the Fitora teleportation incident.",
  },
  {
    id: '10',
    nametag: 'NORN GREYRAT',
    characterImg: '/images/characterDescription/norn/character.png',
    facesImg: '/images/characterDescription/norn/faces.png',
    avatar: '/images/character/norn.png',
    desc: "Daughter of Paul and Zenith and sister of Rudeus. Missing with Paul since the Fitora territory transfer incident. She's searching for her family.",
  },
  {
    id: '11',
    nametag: 'AISHA GREYRAT',
    characterImg: '/images/characterDescription/aisha/character.png',
    facesImg: '/images/characterDescription/aisha/faces.png',
    avatar: '/images/character/aisha.png',
    desc: 'Daughter of Paul and Lilia and half-sister of Rudeus and Norn. After the Fitora teleportation incident, she moved to the Kingdom of Shirone with Lilia.',
  },
  {
    id: '12',
    nametag: 'GHISLANE DEDOLDIA',
    characterImg: '/images/characterDescription/ghislane/character.png',
    facesImg: '/images/characterDescription/ghislane/faces.png',
    avatar: '/images/character/ghislane.png',
    desc: "A beastly swordsman hired by the Boreas Greyrat family to teach swordsmanship to Eris. She is muscular and wears an eye patch over her right eye. She is a former member of the adventurer party 'Black Wolf Fang'.",
  },
  {
    id: '13',
    nametag: 'KISHIRIKA KISHIRISU',
    characterImg: '/images/characterDescription/kishirika/character.png',
    facesImg: '/images/characterDescription/kishirika/faces.png',
    avatar: '/images/character/kishirika.png',
    desc: "She may look like a girl, but she is actually the 'Great Emperor of the Demon World' who leads the demon tribe. She has 12 'demon eyes' in her body and can see through everything.",
  },
  {
    id: '14',
    nametag: 'ORSTED',
    characterImg: '/images/characterDescription/orsted/character.png',
    facesImg: '/images/characterDescription/orsted/faces.png',
    avatar: '/images/character/orsted.png',
    desc: "Dragon God, one of the world's seven most powerful people, the 'Seven World Power'. He is a man with silver hair, golden tricolored eyes, and a swarthy atmosphere. He is feared by all creatures in the world because he is born with a curse that causes them to hate and fear him.",
  },
  {
    id: '15',
    nametag: 'ARUMANFI',
    characterImg: '/images/characterDescription/arumanfi/character.png',
    facesImg: '/images/characterDescription/arumanfi/faces.png',
    avatar: '/images/character/arumanfi.png',
    desc: 'One of the 12 messengers and first servants of Perugius, who resides in the aerial citadel of Chaos Breaker. He can change into light and move, and is skilled at reconnaissance and surprise attacks.',
  },
  {
    id: '16',
    nametag: 'ELINALISE DRAGONROAD',
    characterImg: '/images/characterDescription/elinalise/character.png',
    facesImg: '/images/characterDescription/elinalise/faces.png',
    avatar: '/images/character/elinalise.png',
    desc: "	A former member of the adventurer party 'Black Wolf Fang', she is a warrior of the long-eared tribe. She joins forces with Roxy and Talhand to search for Paul and his family who went missing in a teleportation incident.",
  },
  {
    id: '17',
    nametag: 'TALHAND',
    characterImg: '/images/characterDescription/talhand/character.png',
    facesImg: '/images/characterDescription/talhand/faces.png',
    avatar: '/images/character/talhand.png',
    desc: "Former member of the adventurer party 'Black Wolf Fang'. He is a slow runner and lacks agility, so he wears sturdy armor and uses magic while being attacked by his enemies. He works with Roxy and Elinalise.",
  },
  {
    id: '18',
    nametag: 'GEESE NUKADIA',
    characterImg: '/images/characterDescription/gisu/character.png',
    facesImg: '/images/characterDescription/gisu/faces.png',
    avatar: '/images/character/gisu.png',
    desc: 'A demon tribe with a distinctive monkey face. He is a great gambler, and when he was captured by the Beast Tribe because of cheating, he was forced to take a life of his own. He meets Rudeus in the same prison.',
  },
  {
    id: '19',
    nametag: 'ZANOBA SHIRONE',
    characterImg: '/images/characterDescription/zanoba/character.png',
    facesImg: '/images/characterDescription/zanoba/faces.png',
    avatar: '/images/character/zanoba.png',
    desc: "He is the third prince of the Shirone Kingdom and brother of the seventh prince Pax. He is fascinated by the Roxy doll created by Rudeus and volunteers to become Rudeus' apprentice. He is a godchild born with special abilities and is feared in the castle as the 'Head-Chief Prince'.",
  },
  {
    id: '20',
    nametag: '???',
    characterImg: '/images/characterDescription/nanahoshi/character.png',
    facesImg: '/images/characterDescription/nanahoshi/faces.png',
    avatar: '/images/character/nanahoshi.png',
    desc: 'A mysterious figure in a mask who works with the dragon god Orsted.',
  },
  {
    id: '21',
    nametag: 'MAN-GOD',
    characterImg: '',
    facesImg: '',
    avatar: '/images/character/hitogami.png',
    desc: "An unidentified being who calls himself a 'human god'. He appears in the dreams of a race of 'humans' and speaks to their spirits, but his purpose is unknown.",
  },
];
