export const movieData: {
  id: string;
  name: string;
  thumbail: string;
  youtubeLink: string;
  category: string;
}[] = [
  {
    id: '1',
    name: 'Season 2 preview',
    thumbail: '/images/movie/1.jpg',
    youtubeLink: 'https://youtu.be/tlDF3cfb8lA',
    category: 'preview',
  },
  {
    id: '2',
    name: 'OVA preview',
    thumbail: '/images/movie/2.jpg',
    youtubeLink: 'https://youtu.be/D_u6BZYp93U',
    category: 'preview',
  },
  {
    id: '3',
    name: 'Opening Episode 22',
    thumbail: '/images/movie/3.jpg',
    youtubeLink: 'https://youtu.be/NZjoG-0KGC0',
    category: 'OP/ED',
  },
  {
    id: '4',
    name: 'Episode 23 preview',
    thumbail: '/images/movie/4.jpg',
    youtubeLink: 'https://youtu.be/EJDEqL8efgI',
    category: 'preview',
  },
  {
    id: '5',
    name: 'Episode 21 opening',
    thumbail: '/images/movie/5.jpg',
    youtubeLink: 'https://youtu.be/Ka6lvWvXbhw',
    category: 'OP/ED',
  },
  {
    id: '6',
    name: 'Episode 22 preview',
    thumbail: '/images/movie/6.jpg',
    youtubeLink: 'https://youtu.be/RNfPdVW4wjU',
    category: 'preview',
  },
  {
    id: '7',
    name: 'Episode 20 opening',
    thumbail: '/images/movie/7.jpg',
    youtubeLink: 'https://youtu.be/cb0idLH-CnY',
    category: 'OP/ED',
  },
  {
    id: '8',
    name: 'Episode 21 preview',
    thumbail: '/images/movie/8.jpg',
    youtubeLink: 'https://youtu.be/pdHQO2n3doE',
    category: 'preview',
  },
  {
    id: '9',
    name: 'Episode 19 opening',
    thumbail: '/images/movie/9.jpg',
    youtubeLink: 'https://youtu.be/d79iZcngOGQ',
    category: 'OP/ED',
  },
  {
    id: '10',
    name: 'Turning Point 2 preview',
    thumbail: '/images/movie/10.jpg',
    youtubeLink: 'https://youtu.be/0bGPZxfIHq8',
    category: 'preview',
  },
  {
    id: '11',
    name: 'Episode 20 preview',
    thumbail: '/images/movie/11.jpg',
    youtubeLink: 'https://youtu.be/yVgoUGdg_Fs',
    category: 'preview',
  },
  {
    id: '12',
    name: 'Episode 18 opening',
    thumbail: '/images/movie/12.jpg',
    youtubeLink: 'https://youtu.be/kJFrz2qBy-o',
    category: 'OP/ED',
  },
  {
    id: '13',
    name: 'Episode 19 preview',
    thumbail: '/images/movie/13.jpg',
    youtubeLink: 'https://youtu.be/nh6jJBVlgE0',
    category: 'preview',
  },
  {
    id: '14',
    name: 'Episode 17 opening',
    thumbail: '/images/movie/14.jpeg',
    youtubeLink: 'https://youtu.be/yAj0Oj4lRKk',
    category: 'OP/ED',
  },
  {
    id: '15',
    name: 'Episode 18 preview',
    thumbail: '/images/movie/15.jpeg',
    youtubeLink: 'https://youtu.be/Yzo5-V9w7GM',
    category: 'preview',
  },
  {
    id: '16',
    name: 'Episode 16 opening',
    thumbail: '/images/movie/16.jpeg',
    youtubeLink: 'https://youtu.be/Zf3zKKf1FNU',
    category: 'OP/ED',
  },
  {
    id: '17',
    name: 'Episode 17 preview',
    thumbail: '/images/movie/17.jpeg',
    youtubeLink: 'https://www.youtube.com/watch?v=CtP3JGJDkIk',
    category: 'preview',
  },
  {
    id: '18',
    name: 'Episode 15 opening',
    thumbail: '/images/movie/18.jpeg',
    youtubeLink: 'https://youtu.be/MUgaOXXf58w',
    category: 'OP/ED',
  },
  {
    id: '19',
    name: 'Episode 16 preview',
    thumbail: '/images/movie/19.jpeg',
    youtubeLink: 'https://youtu.be/1XI0R2kjZTQ',
    category: 'preview',
  },
  {
    id: '20',
    name: 'Episode 14 opening',
    thumbail: '/images/movie/20.jpeg',
    youtubeLink: 'https://youtu.be/1vNVI9gINtg',
    category: 'OP/ED',
  },
  {
    id: '21',
    name: 'Episode 15 preview',
    thumbail: '/images/movie/21.jpeg',
    youtubeLink: 'https://youtu.be/dXiwlFmlmrA',
    category: 'preview',
  },
  {
    id: '22',
    name: 'Episode 13 opening',
    thumbail: '/images/movie/22.jpeg',
    youtubeLink: 'https://www.youtube.com/watch?v=sRjYwdmaNNQ',
    category: 'OP/ED',
  },
  {
    id: '23',
    name: 'Episode 14 preview',
    thumbail: '/images/movie/23.jpeg',
    youtubeLink: 'https://youtu.be/fqFbaMYlKu8',
    category: 'preview',
  },
  {
    id: '24',
    name: 'Episode 12 opening',
    thumbail: '/images/movie/24.jpeg',
    youtubeLink: 'https://youtu.be/ZwJZa9mrwBw',
    category: 'OP/ED',
  },
  {
    id: '25',
    name: 'Episode 13 preview',
    thumbail: '/images/movie/25.jpeg',
    youtubeLink: 'https://youtu.be/KMAnA-htb8E',
    category: 'preview',
  },
  {
    id: '26',
    name: 'Ending 2',
    thumbail: '/images/movie/26.jpeg',
    youtubeLink: 'https://www.youtube.com/watch?v=PINgF6rCuME',
    category: 'OP/ED',
  },
  {
    id: '27',
    name: 'VA Interview',
    thumbail: '/images/movie/27.jpg',
    youtubeLink: 'https://youtu.be/N9NLMWR9Q1A',
    category: 'Others',
  },
  {
    id: '28',
    name: 'Episode 12 preview',
    thumbail: '/images/movie/28.jpg',
    youtubeLink: 'https://youtu.be/xp83qhPA4TA',
    category: 'preview',
  },
  {
    id: '29',
    name: 'Episode 11 opening',
    thumbail: '/images/movie/29.jpeg',
    youtubeLink: 'https://youtu.be/BbbRytVhaDs',
    category: 'OP/ED',
  },
  {
    id: '30',
    name: 'Cour 2 preview',
    thumbail: '/images/movie/30.jpeg',
    youtubeLink: 'https://youtu.be/fcSzGKfVkJM',
    category: 'preview',
  },
  {
    id: '31',
    name: 'Episode 11 preview',
    thumbail: '/images/movie/31.png',
    youtubeLink: 'https://youtu.be/2oQS7VrW62g',
    category: 'preview',
  },
  {
    id: '32',
    name: 'Episode 10 preview',
    thumbail: '/images/movie/32.png',
    youtubeLink: 'https://youtu.be/CPD1RIjMS9A',
    category: 'preview',
  },
  {
    id: '33',
    name: 'Episode 9 preview',
    thumbail: '/images/movie/33.jpg',
    youtubeLink: 'https://youtu.be/ZiWbwjQYDT8',
    category: 'preview',
  },
  {
    id: '34',
    name: 'Turning Point 1 preview',
    thumbail: '/images/movie/34.jpg',
    youtubeLink: 'https://youtu.be/BGEIFpAFceg',
    category: 'preview',
  },
  {
    id: '35',
    name: 'Episode 8 preview',
    thumbail: '/images/movie/35.jpg',
    youtubeLink: 'https://youtu.be/dMQtEmAGS7w',
    category: 'preview',
  },
  {
    id: '36',
    name: 'Episode 7 preview',
    thumbail: '/images/movie/36.jpg',
    youtubeLink: 'https://youtu.be/EdqNw382sDk',
    category: 'preview',
  },
  {
    id: '37',
    name: 'Episode 6 preview',
    thumbail: '/images/movie/37.jpg',
    youtubeLink: 'https://youtu.be/XJrTjlNImzc',
    category: 'preview',
  },
  {
    id: '38',
    name: 'Episode 5 preview',
    thumbail: '/images/movie/38.jpg',
    youtubeLink: 'https://youtu.be/xtKL3M-u_OM',
    category: 'preview',
  },
  {
    id: '39',
    name: 'Episode 4 preview',
    thumbail: '/images/movie/39.jpg',
    youtubeLink: 'https://youtu.be/I4HbzXPRAaA',
    category: 'preview',
  },
  {
    id: '40',
    name: 'Episode 3 preview',
    thumbail: '/images/movie/40.jpg',
    youtubeLink: 'https://youtu.be/Tgz5S26oae8',
    category: 'preview',
  },
  {
    id: '41',
    name: 'Ending 1',
    thumbail: '/images/movie/41.jpg',
    youtubeLink: 'https://www.youtube.com/watch?v=3mLWoJF17U4',
    category: 'OP/ED',
  },
  {
    id: '42',
    name: 'Episode 2 preview',
    thumbail: '/images/movie/42.jpg',
    youtubeLink: 'https://youtu.be/KTmhWccOZTM',
    category: 'preview',
  },
  {
    id: '43',
    name: 'Episode 1 preview',
    thumbail: '/images/movie/43.jpg',
    youtubeLink: 'https://youtu.be/O4eKlAAtxAM',
    category: 'preview',
  },
  {
    id: '44',
    name: 'Preview 3',
    thumbail: '/images/movie/44.png',
    youtubeLink: 'https://youtu.be/JoS7Z8MCD6E',
    category: 'preview',
  },
  {
    id: '45',
    name: 'Preview 2',
    thumbail: '/images/movie/45.jpg',
    youtubeLink: 'https://youtu.be/PUzRndqfHbA',
    category: 'preview',
  },
  {
    id: '46',
    name: 'Preview 1',
    thumbail: '/images/movie/46.jpg',
    youtubeLink: 'https://youtu.be/Qx01pn9l-6g',
    category: 'preview',
  },
];
