export const soundtrackData2: {
  name: string;
}[] = [
  { name: '1 Adventure.' },
  { name: '2 Thinking' },
  { name: '3 Gambling' },
  { name: '4 Mischief.' },
  { name: '5 A bad situation.' },
  { name: '6 Where Magic Gathers.' },
  { name: "7 Ruijerd's anger." },
  { name: '8 On the Palm' },
  { name: '9 The Farewell of Tona and Eris' },
  { name: '10 The Holy Land of Milis.' },
  { name: '11 The First Sea' },
  { name: '12 The Great Demon Emperor Kishirika Kishirisu!' },
  { name: '13 Ghislaine.' },
  { name: '14 To gain trust' },
  { name: '15 Windport' },
  { name: '16 Smuggling organization' },
  { name: '17 Meeting of Operations' },
  { name: '18 The Power of a Smile' },
  { name: '19 Comfortable Prison' },
  { name: '20 Seniors and newcomers' },
  { name: '21 Doldiers' },
  { name: '22 Co-op' },
  { name: '23 Reunion' },
  { name: '24 Adventurers' },
  { name: '25 Comfort' },
  { name: '26 Waiting' },
  { name: '27 The Sacred World' },
  { name: '28 Cielone Royal Palace' },
  { name: '29 Secret maneuver' },
  { name: '30 No way!' },
  { name: "31 Traveller's Song -EP17 Inst Ver." },
  { name: '32 Mind for Roxy' },
  { name: '33 The Power of Zanoba' },
  { name: '34 An Encounter with Overwhelming Power' },
  { name: 'Included only in the distributed version.' },
  { name: 'Distribution start date' },
  { name: 'January 19, 2021 (Wednesday) Start of distribution' },
  { name: 'Distribution destination UPL' },
  {
    name: 'Distribution will begin on January 19, 2021 (Wed.) [UPL] Available on iTunes, mora, Apple Music, Spotify, and other music distribution sites.',
  },
  { name: 'Package Included Version' },
  {
    name: 'Includes a total of 37 tracks, including tracks not included in the distributed version!',
  },
];
