export const soundtrackData: {
  name: string;
}[] = [
  {
    name: '1. A Lesson in Witchcraft',
  },
  { name: '2 In a world where magic exists' },
  { name: '3 Chanting' },
  { name: "4 Rudy's Blunder" },
  { name: '5 The Little Tutor Roxy' },
  { name: '6 Reincarnation without a job' },
  { name: '7 A World Unseen' },
  { name: '8 Gift from Roxy' },
  { name: '9 Despair Outside' },
  { name: "10 Roxy's Last Lesson" },
  { name: "11 The Master's Charm" },
  { name: '12 Days of the Greyrats' },
  { name: '13 Friends' },
  { name: '14 Unexpected reality' },
  { name: "15 Eris's smile" },
  { name: "16 Sylphy's Tears" },
  { name: '17 Letter from Roxy' },
  { name: '18 Only (Acoustic Ver.)' },
  { name: '19 Paul VS Rudy' },
  { name: '20 Alone with Ghislaine' },
  { name: '21 Eris gets angry' },
  { name: '23 Sauros appears' },
  { name: '24 Please Nyan' },
  { name: "25 Guilene's guidance" },
  { name: '26 Swordsmanship instruction' },
  { name: '27 Dance without magic' },
  { name: '28 Promise after 5 years!' },
  { name: "29 Hitogami's advice" },
  { name: '30 An Important Companion' },
  { name: 'Included only in the distributed version.' },
  { name: 'Distribution start date' },
  { name: 'April 21, 2021 (Thursday) Start of distribution' },
  { name: 'Distribution destination UPL' },
  {
    name: 'Available on iTunes, mora, Apple Music, Spotify and other music distribution sites',
  },
  { name: 'Package Included Version' },
  {
    name: 'Includes a total of 37 tracks, including tracks not included in the distributed version!',
  },
];
